#requires -Version 7.0
<#
  Phase 2 of 3: FIX
  - Set all package versions to 0.5.0
  - Mark internal tooling (gate-runner-core, testing) as private:true
  - Generate publishable-whitelist.yaml
  - Archive the major-bump changeset
  - Sync lockfile
#>
param(
  [string]$TargetVersion = "0.5.0",
  [switch]$PrivateSandboxSecurity  # set if plugin-sandbox/security are Pro, not OSS stubs
)
$ErrorActionPreference = "Stop"

function Log($m){ Write-Host "[02-fix] $m" -ForegroundColor Cyan }
function Ok($m){ Write-Host "  OK  $m" -ForegroundColor Green }
function Warn($m){ Write-Host "  !   $m" -ForegroundColor Yellow }

# Internal tooling — never publish (per CR: not a shipped feature)
$INTERNAL = @("gate-runner-core","testing")
if($PrivateSandboxSecurity){ $INTERNAL += @("plugin-sandbox","security") }

if(-not (Test-Path "package.json")){ Write-Host "Run from repo root" -ForegroundColor Red; exit 1 }

# 1. Scan for major-bump changesets
Log "Scanning changesets for 'major' bumps"
Get-ChildItem ".changeset/*.md" -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -ne "README.md" } |
  ForEach-Object {
    if((Get-Content $_.FullName -Raw) -match "(?m):\s*major"){
      Warn "MAJOR bump found in $($_.Name) — will be archived"
    }
  }

# 2. Set versions + private flags
Log "Setting versions=$TargetVersion and private flags"
Log "Internal (private, NOT published): $($INTERNAL -join ', ')"
$publishable = @()

Get-ChildItem "packages" -Directory | ForEach-Object {
  $pj = Join-Path $_.FullName "package.json"
  if(-not (Test-Path $pj)){ return }
  $raw = Get-Content $pj -Raw
  $pkg = $raw | ConvertFrom-Json
  if(-not $pkg.name){ return }
  $short = $pkg.name -replace "@orqenix/",""

  # Skip non-orqenix packages
  if($pkg.name -notlike "@orqenix/*"){ return }

  $pkg.version = $TargetVersion

  if($INTERNAL -contains $short){
    $pkg | Add-Member -NotePropertyName private -NotePropertyValue $true -Force
    Warn "PRIVATE: $($pkg.name)"
  } else {
    if($pkg.PSObject.Properties.Name -contains "private"){ $pkg.private = $false }
    # Ensure publishConfig.access = public
    if($pkg.PSObject.Properties.Name -notcontains "publishConfig"){
      $pkg | Add-Member -NotePropertyName publishConfig -NotePropertyValue ([PSCustomObject]@{access="public"}) -Force
    } else {
      $pkg.publishConfig | Add-Member -NotePropertyName access -NotePropertyValue "public" -Force
    }
    $publishable += $pkg.name
    Ok "publishable: $($pkg.name) -> $TargetVersion"
  }

  ($pkg | ConvertTo-Json -Depth 100) | Set-Content $pj -Encoding utf8
}

# 3. Write whitelist
Log "Writing publishable-whitelist.yaml"
$wlDir = ".orqenix/release"
New-Item -ItemType Directory -Force -Path $wlDir | Out-Null
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Public OSS packages (Apache 2.0). Per CR v7.1 Ch 21 + CR v7.2.")
[void]$sb.AppendLine("# Internal tooling is private:true and excluded from npm.")
[void]$sb.AppendLine("# Generated by 02-fix.ps1 at $(Get-Date -Format o)")
[void]$sb.AppendLine("oss:")
foreach($n in ($publishable | Sort-Object)){ [void]$sb.AppendLine("  - `"$n`"") }
$sb.ToString() | Set-Content (Join-Path $wlDir "publishable-whitelist.yaml") -Encoding utf8
Ok "Whitelist: $($publishable.Count) public packages"

# 4. Archive changesets (we set versions manually, no changeset version step)
Log "Archiving changesets"
$arch = ".changeset/archived"
New-Item -ItemType Directory -Force -Path $arch | Out-Null
Get-ChildItem ".changeset/*.md" -ErrorAction SilentlyContinue |
  Where-Object { $_.Name -ne "README.md" } |
  ForEach-Object { Move-Item $_.FullName (Join-Path $arch $_.Name) -Force; Ok "archived: $($_.Name)" }

# 5. Sync lockfile
Log "Syncing lockfile"
$env:NPM_CONFIG_IGNORE_SCRIPTS = "true"
pnpm install --lockfile-only
Ok "Lockfile synced"

Log "PHASE 2 COMPLETE."
Log "Internal (private): $($INTERNAL.Count) | Publishable: $($publishable.Count)"
Log ""
Log "NEXT: commit, then republish:"
Log "  git add -A"
Log "  git commit -m 'fix(release): reset 0.5.0, private internal pkgs, add whitelist'"
Log "  git push"
Log "  pwsh ./scripts/release/03-republish.ps1"
