import { describe, it, expect } from "vitest";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { compileSkillForOpenCode, readSkillSource } from "../src/sync/skill-compiler.js";

describe("skill-compiler", () => {
  it("reads frontmatter and body", async () => {
    const dir = mkdtempSync(join(tmpdir(), "orqenix-skill-"));
    const path = join(dir, "SKILL.md");
    writeFileSync(path, `---\nname: my-skill\ndescription: Does things\n---\n## Body\nHi`);
    const skill = await readSkillSource(path, "my-skill");
    expect(skill.frontmatter.name).toBe("my-skill");
    expect(skill.frontmatter.description).toBe("Does things");
    expect(skill.body).toContain("## Body");
    expect(skill.contentHash).toMatch(/^blake3:[a-f0-9]+$/);
  });

  it("compiles with marker and only recognized fields", async () => {
    const dir = mkdtempSync(join(tmpdir(), "orqenix-skill-"));
    const path = join(dir, "SKILL.md");
    writeFileSync(
      path,
      `---\nname: x\ndescription: y\nlicense: MIT\nmetadata:\n  a: "1"\n  b: 2\nrogue: drop-me\n---\nBody`,
    );
    const skill = await readSkillSource(path, "x");
    const out = compileSkillForOpenCode(skill, { teamName: "t", teamVersion: "1" });
    expect(out).toContain("AUTO-GENERATED BY ORQENIX");
    expect(out).toContain("name: x");
    expect(out).toContain("description: y");
    expect(out).toContain("license: MIT");
    expect(out).toContain("a: ");
    expect(out).toContain("b: ");
    expect(out).not.toContain("rogue");
  });

  it("coerces non-string metadata values to string", async () => {
    const dir = mkdtempSync(join(tmpdir(), "orqenix-skill-"));
    const path = join(dir, "SKILL.md");
    writeFileSync(
      path,
      `---\nname: x\ndescription: y\nmetadata:\n  count: 42\n  flag: true\n---\nBody`,
    );
    const skill = await readSkillSource(path, "x");
    const out = compileSkillForOpenCode(skill);
    expect(out).toContain("count: 42");
    expect(out).toContain("flag: true");
  });
});
