import { describe, it, expect, beforeEach } from "vitest";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SyncEngine } from "../src/sync/engine.js";
import { DEFAULT_CONFIG } from "../src/config/defaults.js";

describe("sync engine", () => {
  let projectRoot: string;

  beforeEach(() => {
    projectRoot = mkdtempSync(join(tmpdir(), "orqenix-sync-"));
    mkdirSync(join(projectRoot, ".orqenix", "teams", "test-team", "agents"), { recursive: true });
    mkdirSync(join(projectRoot, ".opencode", "agents"), { recursive: true });

    writeFileSync(
      join(projectRoot, ".orqenix", "teams", "test-team", "team.json"),
      JSON.stringify({
        name: "test-team",
        version: "1.0.0",
        description: "fixture",
        namingPrefix: "test-team",
        teamLead: { role: "lead", file: "agents/lead.md", mode: "primary" },
        agents: {
          core: [{ role: "worker", file: "agents/worker.md", mode: "subagent" }],
          optional: [],
        },
        defaultSkills: [],
        defaultMCP: [],
        syncTargets: {
          opencode: {
            enabled: true,
            outputDir: ".opencode/agents",
            filenamePattern: "{prefix}-{role}.md",
          },
        },
      }),
    );

    writeFileSync(
      join(projectRoot, ".orqenix", "teams", "test-team", "agents", "lead.md"),
      `---\ndescription: Lead\nmode: primary\n---\n# Lead\nBody`,
    );
    writeFileSync(
      join(projectRoot, ".orqenix", "teams", "test-team", "agents", "worker.md"),
      `---\ndescription: Worker\nmode: subagent\n---\n# Worker\nBody`,
    );
  });

  it("compiles team into OpenCode agent files", async () => {
    const engine = new SyncEngine(projectRoot, DEFAULT_CONFIG);
    const results = await engine.syncAll();
    expect(results).toHaveLength(1);
    expect(results[0]!.written).toEqual(
      expect.arrayContaining(["test-team-lead.md", "test-team-worker.md"]),
    );

    const leadOut = readFileSync(
      join(projectRoot, ".opencode", "agents", "test-team-lead.md"),
      "utf-8",
    );
    expect(leadOut).toContain("AUTO-GENERATED BY ORQENIX");
    expect(leadOut).toContain("description: Lead");
    expect(leadOut).toContain("# Lead");
  });

  it("writes sync state record", async () => {
    const engine = new SyncEngine(projectRoot, DEFAULT_CONFIG);
    await engine.syncAll();
    const statePath = join(projectRoot, ".orqenix", "sync", "agents.json");
    expect(existsSync(statePath)).toBe(true);
    const state = JSON.parse(readFileSync(statePath, "utf-8"));
    expect(state.agents["test-team-lead"]).toBeDefined();
  });
});
