// SPDX-License-Identifier: Apache-2.0
// @orqenix/skill-genesis , Code synthesizer
//
// Synthesizes executable code stubs in TS/Python/shell from a candidate's
// action sequence + inferred parameters. Per CR v8.0 Section 9.4.4.

import type { ImplementationLanguage } from "@orqenix/plugin-core";
import type { ObservationEvent } from "@orqenix/self-learning-observer";
import type { InferredParameter } from "./types";

export class CodeSynthesizer {
  /**
   * Chooses the implementation language based on the dominant action kinds.
   */
  inferLanguage(events: ObservationEvent[]): ImplementationLanguage {
    const shellCount = events.filter((e) => e.action_kind === "shell_command").length;
    const total = events.length || 1;
    if (shellCount / total > 0.6) return "shell";
    // Check for python-specific signals in payloads
    const hasPython = events.some((e) =>
      JSON.stringify(e.action_payload).match(/\.py\b|pytest|pip\b|python/),
    );
    if (hasPython) return "python";
    return "typescript";
  }

  /**
   * Synthesizes a code stub for the given language. The stub reconstructs the
   * observed action sequence as a parameterized, runnable skill.
   */
  synthesize(input: {
    skillName: string;
    actionKinds: string[];
    parameters: InferredParameter[];
    sampleEvents: ObservationEvent[];
    language: ImplementationLanguage;
  }): string {
    switch (input.language) {
      case "shell":
        return this.synthesizeShell(input);
      case "python":
        return this.synthesizePython(input);
      default:
        return this.synthesizeTypeScript(input);
    }
  }

  private synthesizeTypeScript(input: {
    skillName: string;
    actionKinds: string[];
    parameters: InferredParameter[];
    sampleEvents: ObservationEvent[];
  }): string {
    const paramTypes = input.parameters
      .map((p) => `  ${p.name}${p.required ? "" : "?"}: ${this.tsType(p.type)};`)
      .join("\n");
    const steps = input.actionKinds
      .map(
        (kind, i) =>
          `    // Step ${i + 1}: ${kind.replace(/_/g, " ")}\n    // TODO: implement ${kind} from observed pattern`,
      )
      .join("\n");

    return `// SPDX-License-Identifier: Apache-2.0
// Generated by @orqenix/skill-genesis from observed workflow pattern.
// Review + complete the TODOs before verifying.

export interface Input {
${paramTypes || "  // (no variable parameters inferred)"}
}

export interface Output {
  success: boolean;
  result?: unknown;
}

/**
 * Skill: ${input.skillName}
 * Derived from a recurring ${input.actionKinds.length}-step workflow.
 */
export async function invoke(input: Input): Promise<Output> {
${steps}

  return { success: true };
}
`;
  }

  private synthesizePython(input: {
    skillName: string;
    actionKinds: string[];
    parameters: InferredParameter[];
  }): string {
    const params = input.parameters
      .map((p) => `    ${p.name}: ${this.pyType(p.type)}${p.required ? "" : " = None"}`)
      .join(",\n");
    const steps = input.actionKinds
      .map(
        (kind, i) =>
          `    # Step ${i + 1}: ${kind.replace(/_/g, " ")}\n    # TODO: implement ${kind} from observed pattern`,
      )
      .join("\n");

    return `# SPDX-License-Identifier: Apache-2.0
# Generated by @orqenix/skill-genesis from observed workflow pattern.
# Review + complete the TODOs before verifying.

def invoke(
${params || "    # (no variable parameters inferred)"}
):
    """Skill: ${input.skillName} , derived from a recurring ${input.actionKinds.length}-step workflow."""
${steps}

    return {"success": True}
`;
  }

  private synthesizeShell(input: {
    skillName: string;
    actionKinds: string[];
    sampleEvents: ObservationEvent[];
  }): string {
    // Extract observed shell commands from samples (already PII-redacted)
    const commands = input.sampleEvents
      .filter((e) => e.action_kind === "shell_command")
      .map((e) => (e.action_payload.command as string) ?? "")
      .filter(Boolean)
      .slice(0, input.actionKinds.length);

    const body =
      commands.length > 0
        ? commands.map((c, i) => `# Step ${i + 1}\n${c}`).join("\n\n")
        : input.actionKinds
            .map((k, i) => `# Step ${i + 1}: ${k}\n# TODO: add command`)
            .join("\n\n");

    return `#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Generated by @orqenix/skill-genesis from observed workflow pattern.
# Review the commands (PII redacted) before verifying.
set -euo pipefail

# Skill: ${input.skillName}
${body}
`;
  }

  private tsType(t: InferredParameter["type"]): string {
    switch (t) {
      case "number":
        return "number";
      case "boolean":
        return "boolean";
      case "array":
        return "unknown[]";
      case "object":
        return "Record<string, unknown>";
      default:
        return "string";
    }
  }

  private pyType(t: InferredParameter["type"]): string {
    switch (t) {
      case "number":
        return "float";
      case "boolean":
        return "bool";
      case "array":
        return "list";
      case "object":
        return "dict";
      default:
        return "str";
    }
  }
}
