/**
 * Lightweight smoke test that exercises the cross-platform paths of Phase 1.
 * Run this before starting Phase 2:  pnpm tsx scripts/cross-platform-smoke.ts
 *
 * It does NOT require a published package — it uses local source.
 */

import { spawnSync } from "node:child_process";
import { mkdtempSync, rmSync, existsSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(import.meta.url), "../..");
const CLI = join(ROOT, "packages/cli/bin/orqenix.js");
const DEV_TEAM = join(ROOT, "packages/teams-built-in/dev-team");

if (!existsSync(CLI)) {
  console.error(`CLI binary not built. Run: pnpm build`);
  process.exit(1);
}

console.log(`Platform: ${process.platform} (${process.arch})`);
console.log(`Node:     ${process.versions.node}`);
console.log(`CLI:      ${CLI}`);
console.log("");

const trial = mkdtempSync(join(tmpdir(), "orqenix-smoke-"));
console.log(`Trial dir: ${trial}`);

function run(label: string, args: string[], opts: { allowFail?: boolean } = {}): void {
  process.stdout.write(`  ${label} ... `);
  const r = spawnSync("node", [CLI, ...args], {
    cwd: trial,
    encoding: "utf-8",
    shell: false,
  });
  if (r.status !== 0 && !opts.allowFail) {
    console.log("✗");
    console.error(`    stdout: ${r.stdout}`);
    console.error(`    stderr: ${r.stderr}`);
    process.exit(1);
  }
  console.log("✓");
}

try {
  // 1. Init creates the directory structure
  run("orqenix init", ["init", "--cwd", trial]);

  // Check structure
  const expectedDirs = [
    ".orqenix",
    ".orqenix/teams",
    ".orqenix/scope",
    ".orqenix/knowledge",
    ".orqenix/memory",
    ".orqenix/cache",
    ".orqenix/sync",
    ".orqenix/logs",
    ".opencode",
    ".opencode/agents",
    ".opencode/skills",
    ".opencode/plugin",
  ];
  for (const d of expectedDirs) {
    if (!existsSync(join(trial, d))) {
      console.error(`✗  Missing dir: ${d}`);
      process.exit(1);
    }
  }
  console.log("  directory structure ... ✓");

  // 2. opencode.json registers plugin
  const oc = JSON.parse(readFileSync(join(trial, "opencode.json"), "utf-8"));
  if (!Array.isArray(oc.plugin) || !oc.plugin.includes("@orqenix/opencode-plugin")) {
    console.error("✗  opencode.json missing @orqenix/opencode-plugin in plugin array");
    process.exit(1);
  }
  console.log("  opencode.json plugin registered ... ✓");

  // 3. AGENTS.md created
  if (!existsSync(join(trial, "AGENTS.md"))) {
    console.error("✗  AGENTS.md not created");
    process.exit(1);
  }
  console.log("  AGENTS.md created ... ✓");

  // 4. doctor runs (allowed to warn — outside a git repo)
  run("orqenix doctor", ["doctor", "--cwd", trial, "--no-port-check"], { allowFail: true });

  // 5. Install dev-team from local path
  run("orqenix team install dev-team", ["team", "install", DEV_TEAM, "--cwd", trial]);

  // 6. Sync writes 6 agent files
  const synced = ["lead", "builder", "inspector", "navigator", "debugger", "researcher"];
  for (const role of synced) {
    const p = join(trial, ".opencode", "agents", `dev-team-${role}.md`);
    if (!existsSync(p)) {
      console.error(`✗  Synced agent missing: dev-team-${role}.md`);
      process.exit(1);
    }
    const content = readFileSync(p, "utf-8");
    if (!content.includes("AUTO-GENERATED BY ORQENIX")) {
      console.error(`✗  ${role}: missing auto-generated marker`);
      process.exit(1);
    }
  }
  console.log("  6 agents synced with marker ... ✓");

  // 7. Verify sync state file
  const statePath = join(trial, ".orqenix", "sync", "agents.json");
  if (!existsSync(statePath)) {
    console.error("✗  sync state file missing");
    process.exit(1);
  }
  const state = JSON.parse(readFileSync(statePath, "utf-8"));
  if (!state.agents["dev-team-lead"]) {
    console.error("✗  sync state missing dev-team-lead record");
    process.exit(1);
  }
  console.log("  sync state tracked ... ✓");

  // 8. team list shows 1 team
  run("orqenix team list", ["team", "list", "--cwd", trial]);

  // 9. sync --verify passes (no drift)
  run("orqenix sync --verify", ["sync", "--cwd", trial, "--verify"]);

  // 10. sync --dry-run is a no-op the second time
  run("orqenix sync --dry-run", ["sync", "--cwd", trial, "--dry-run"]);

  // 11. team validate dev-team
  run("orqenix team validate dev-team", ["team", "validate", "dev-team", "--cwd", trial]);

  console.log("");
  console.log(`✓ Cross-platform smoke test passed on ${process.platform}`);
} finally {
  rmSync(trial, { recursive: true, force: true });
}
